;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cider-load-buffer
	kill-region
	paredit-delete-char
	paredit-doublequote
	paredit-forward-slurp-sexp
	paredit-open-round
	paredit-open-square
	))

(setq mc/cmds-to-run-once
      '(
	))
