;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sexp
        cider-load-buffer
        counsel-yank-pop
        forward-sexp
        indent-for-tab-command
        kill-region
        kill-sentence
        kill-sexp
        mark-sexp
        markdown-cycle
        my-paredit-delete
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-cycle
        org-delete-char
        org-delete-indentation
        org-end-of-line
        org-kill-line
        org-self-insert-command
        org-yank
        paredit-C-j
        paredit-backward
        paredit-delete-char
        paredit-doublequote
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-splice-sexp
        undo-redo
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        counsel-M-x
        handle-switch-frame
        ignore-preserving-kill-region
        ivy-switch-buffer
        lsp-ui-doc--handle-mouse-movement
        paredit-kill
        xref-find-definitions
        ))
